Adds @NoQualifierParameter and -AdefaultHasQualifierParameter option
smillst/checker-framework pull request #19
Opened 2019-12-09 00:11 UTC by jwaataja

This adds the ability to turn on `@HasQualifierParameter` for all classes whose fully qualified name matches a regular expression. For example, `-AdefaultHasQualifierParameter=org.checkerframework.checker.determinism.qual.NonDet:randoop.*`, would turn on `@HasQualifierParameter` for all classes in the randoop package by default.

Also adds a new annotation, `@NoQualifierParameter`, which indicates no implicit qualifier parameter. The purpose is so that if `@HasQualifierParameter` is enabled by default with the above option, it can be disabled for specific classes.

2019-12-18 16:30 UTC, smillst requested changes
Instead of using a command line option, the defaulting should be changed via a declaration annotation that can be applied to packages.   See org.checkerframework.framework.qual.DefaultQualifier for an example of changing defaulting based on package.

2019-12-18 16:30 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> +            if (!hasConflictingQualifierParameter
This if statement is confusing, because the error is reported if `hasConflictingQualifierParameter` is false.  That variable should be renamed to something like `conflictingErrorReported`.

2019-12-22 07:40 UTC, jwaataja commented
I changed this to use a package annotation `@DefaultHasQualifierParameter`. What do you think about simply allowing `@HasQualifierParameter` to be written on packages and classes instead of having a specialized annotation for it?

2019-12-28 20:05 UTC, mernst commented
> I changed this to use a package annotation `@DefaultHasQualifierParameter`. What do you think about simply allowing `@HasQualifierParameter` to be written on packages and classes instead of having a specialized annotation for it?

I think permitting the annotation to be written in multiple locations is better than introducing an additional annotation for that purpose.

2020-01-09 22:00 UTC, smillst requested changes

2020-01-09 22:00 UTC, smillst commented on checker/tests/determinism/TestNoQualifierParameterConflicting.java
> +import java.util.*;
Should this test case be removed? It's using the Determinism Checker.

2020-01-09 22:00 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
>              AnnotationMirror annotationMirror = AnnotationBuilder.fromName(elements, qual);
Calling `AnnotationBuilder#fromName` might create an annotation that is missing values and could in the future cause an exception to be thrown.  (See https://github.com/typetools/checker-framework/pull/2970) Your pull request made me realize that I need to rewrite this code to use `isSupportedQualifier(Class<? extends java.lang.annotation.Annotation>)` and rewrite `hasQualifierParameterInHierarchy` to use `AnnotatedTypeFactory#areSameByClass`. (Both of these methods merged into master last week.) I think I can do this after this pull request is merged.

2020-01-09 22:00 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> +     * @param elementAnnotation the class for an annotation that's written on elements, which takes
`annoClass` is a better name.  `elementAnnotation` makes me think the type of the parameter is `Element`.

2020-01-09 22:00 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> +     *     as its arguments other annotations
It doesn't take other annotations as arguments.  Its value element is a list of annotation classes.

2020-01-09 22:00 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
> +     * Returns the set of supported annotations listed inside a specified annotation written on the
`listed inside` is unclear.  I think you mean this returns a set of annotation mirrors corresponding to the annotation classes listed in the value element of annotation with class elementAnnotation on element.

2020-01-09 22:02 UTC, smillst commented
@jwaataja I'm having a hard time remembering to check if this is ready for review.  Could you please send me an email when you are ready for me to review this again? Thanks!

2020-01-16 05:58 UTC, jwaataja commented on checker/tests/determinism/TestNoQualifierParameterConflicting.java
> +import java.util.*;
It should be there. I rewrote it to use the Tainting checker and moved it to the correct location.

2020-01-16 06:12 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
>              AnnotationMirror annotationMirror = AnnotationBuilder.fromName(elements, qual);
Okay, so does that mean I should leave it as is for now?

2020-01-16 19:47 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
>              AnnotationMirror annotationMirror = AnnotationBuilder.fromName(elements, qual);
Yes!

2020-01-16 19:49 UTC, smillst approved these changes

2020-01-16 19:50 UTC, smillst commented
@jwaataja Could you please edit the pull request description and title to match the current implementation?

2020-01-16 23:38 UTC, jwaataja commented
Okay, I update them.

2020-01-16 23:40 UTC, merged